version: '3.8'
services:
  scraper_app:
    container_name: scraper_app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/go/src/app
    depends_on:
      - quotes_db
    links:
      - quotes_db

  quotes_db:
    container_name: quotes_db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  quotes_db: