name: Build Modified GoFiber Recipes

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - "**.md"

jobs:
  builds:
    strategy:
      matrix:
        go-version:
          - oldstable
          - stable
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history so diffs can be performed

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get changed directories
        id: get_changed_dirs
        run: |
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '/.*\.go')
          if [ -n "$files" ]; then
            echo "::set-output name=dirs::$(echo "$files" | xargs -n 1 dirname | sort -u)"
          else
            echo "::set-output name=dirs::"
          fi

      - name: Run go vet for changed directories
        run: |
          if [ -n "${{ steps.get_changed_dirs.outputs.dirs }}" ]; then
            echo "${{ steps.get_changed_dirs.outputs.dirs }}" | xargs -n 1 -P 4 bash -c 'if [ -f "$0/go.mod" ]; then (cd $0; go vet ./...); fi'
          fi

      - name: Run go build for changed directories
        run: |
          if [ -n "${{ steps.get_changed_dirs.outputs.dirs }}" ]; then
            echo "${{ steps.get_changed_dirs.outputs.dirs }}" | xargs -n 1 -P 4 bash -c 'if [ -f "$0/go.mod" ]; then (cd $0; go build ./...); fi'
          fi
