name: Build Modified GoFiber Recipes

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - "**.md"

jobs:
  builds:
    strategy:
      matrix:
        go-version:
          - oldstable
          - stable
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history so diffs can be performed

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Get changed directories
        id: get_changed_dirs
        run: |
          echo "::set-output name=dirs::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '/.*\.go' | xargs -n 1 dirname | sort -u | xargs)"

      - name: Run go vet for changed directories
        run: |
          for dir in ${{ steps.get_changed_dirs.outputs.dirs }}; do
            if [ -f "${dir}/go.mod" ]; then
              (cd $dir; go vet ./...);
            fi
          done

      - name: Run go build for changed directories
        run: |
          for dir in ${{ steps.get_changed_dirs.outputs.dirs }}; do
            if [ -f "${dir}/go.mod" ]; then
              (cd $dir; go build ./...);
            fi
          done
